version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.1
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "ELASTIC_PASSWORD=your_password"
      - "ELASTIC_USERNAME=your_username"
    ports:
      - 9200:9200
  logstash:
    image: docker.elastic.co/logstash/logstash:8.1.1
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana:8.1.1
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
