version: '3'
services:
  nonprod_cloudtrail:
    container_name: conatiner-name
    # image: logstash:7.16.1
    restart: always
    build:
      context: ./
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash.template.json:/usr/share/logstash/templates/logstash.template.json
      - ./nlogstash.yml:/usr/share/logstash/config/logstash.yml
    ports:
      - 5064:5044
    stdin_open: true
    tty: true
    network_mode: bridge
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    environment:
      - logger.level=WARN


    